const TEXTS = [
  {
    id: "intro",
    title: "自我介绍",
    titleEn: "Self-introduction",
    level: 1,
    english: "Hello! My name is Xiaoming. I am a student. I am twenty years old. I live in Beijing. I like to read books and drink tea.",
    paragraphs: [
      [
        { zh: "你好", py: "nǐ hǎo", en: "hello" },
        { zh: "！", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "叫", py: "jiào", en: "to be called" },
        { zh: "小明", py: "Xiǎomíng", en: "Xiaoming (name)" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "是", py: "shì", en: "to be" },
        { zh: "学生", py: "xuéshēng", en: "student" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "二十", py: "èrshí", en: "twenty" },
        { zh: "岁", py: "suì", en: "years old" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "住在", py: "zhù zài", en: "to live in" },
        { zh: "北京", py: "Běijīng", en: "Beijing" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "喜欢", py: "xǐhuan", en: "to like" },
        { zh: "看书", py: "kàn shū", en: "to read books" },
        { zh: "和", py: "hé", en: "and" },
        { zh: "喝茶", py: "hē chá", en: "to drink tea" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "day",
    title: "我的一天",
    titleEn: "My day",
    level: 1,
    english: "I get up at seven in the morning. I brush my teeth, wash my face, then eat breakfast. At eight I go to school. In the afternoon I go home and do homework. In the evening I watch TV and go to bed at ten.",
    paragraphs: [
      [
        { zh: "早上", py: "zǎoshang", en: "morning" },
        { zh: "七点", py: "qī diǎn", en: "seven o'clock" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "起床", py: "qǐchuáng", en: "to get up" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "刷牙", py: "shuā yá", en: "to brush teeth" },
        { zh: "，", py: "", en: "" },
        { zh: "洗脸", py: "xǐ liǎn", en: "to wash one's face" },
        { zh: "，", py: "", en: "" },
        { zh: "然后", py: "ránhòu", en: "then" },
        { zh: "吃", py: "chī", en: "to eat" },
        { zh: "早饭", py: "zǎofàn", en: "breakfast" },
        { zh: "。", py: "", en: "" },
        { zh: "八点", py: "bā diǎn", en: "eight o'clock" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "学校", py: "xuéxiào", en: "school" },
        { zh: "。", py: "", en: "" },
        { zh: "下午", py: "xiàwǔ", en: "afternoon" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "回家", py: "huí jiā", en: "to go home" },
        { zh: "写", py: "xiě", en: "to write" },
        { zh: "作业", py: "zuòyè", en: "homework" },
        { zh: "。", py: "", en: "" },
        { zh: "晚上", py: "wǎnshang", en: "evening" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "看", py: "kàn", en: "to watch / to read" },
        { zh: "电视", py: "diànshì", en: "television" },
        { zh: "，", py: "", en: "" },
        { zh: "十点", py: "shí diǎn", en: "ten o'clock" },
        { zh: "睡觉", py: "shuìjiào", en: "to sleep" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "family",
    title: "我的家人",
    titleEn: "My family",
    level: 1,
    english: "There are four people in my family: dad, mom, older sister, and me. Dad is a teacher. Mom works at a hospital. Older sister graduates from university this year. We love each other very much.",
    paragraphs: [
      [
        { zh: "我家", py: "wǒ jiā", en: "my family / my home" },
        { zh: "有", py: "yǒu", en: "to have" },
        { zh: "四口人", py: "sì kǒu rén", en: "four people (family)" },
        { zh: "：", py: "", en: "" },
        { zh: "爸爸", py: "bàba", en: "dad" },
        { zh: "、", py: "", en: "" },
        { zh: "妈妈", py: "māma", en: "mom" },
        { zh: "、", py: "", en: "" },
        { zh: "姐姐", py: "jiějie", en: "older sister" },
        { zh: "和", py: "hé", en: "and" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "。", py: "", en: "" },
        { zh: "爸爸", py: "bàba", en: "dad" },
        { zh: "是", py: "shì", en: "to be" },
        { zh: "老师", py: "lǎoshī", en: "teacher" },
        { zh: "。", py: "", en: "" },
        { zh: "妈妈", py: "māma", en: "mom" },
        { zh: "在", py: "zài", en: "at / in" },
        { zh: "医院", py: "yīyuàn", en: "hospital" },
        { zh: "工作", py: "gōngzuò", en: "to work" },
        { zh: "。", py: "", en: "" },
        { zh: "姐姐", py: "jiějie", en: "older sister" },
        { zh: "今年", py: "jīnnián", en: "this year" },
        { zh: "大学", py: "dàxué", en: "university" },
        { zh: "毕业", py: "bìyè", en: "to graduate" },
        { zh: "。", py: "", en: "" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "很", py: "hěn", en: "very" },
        { zh: "相爱", py: "xiāng'ài", en: "to love each other" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "shop",
    title: "去商店",
    titleEn: "Going to the shop",
    level: 2,
    english: "Today I went to the shop to buy things. The apples were very fresh, so I bought six. I also bought a bottle of milk and a loaf of bread. Altogether it was twenty-five yuan.",
    paragraphs: [
      [
        { zh: "今天", py: "jīntiān", en: "today" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "商店", py: "shāngdiàn", en: "shop" },
        { zh: "买东西", py: "mǎi dōngxi", en: "to buy things" },
        { zh: "。", py: "", en: "" },
        { zh: "苹果", py: "píngguǒ", en: "apple" },
        { zh: "很", py: "hěn", en: "very" },
        { zh: "新鲜", py: "xīnxiān", en: "fresh" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "买了", py: "mǎi le", en: "bought" },
        { zh: "六个", py: "liù ge", en: "six (items)" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "也", py: "yě", en: "also" },
        { zh: "买了", py: "mǎi le", en: "bought" },
        { zh: "一瓶", py: "yì píng", en: "one bottle of" },
        { zh: "牛奶", py: "niúnǎi", en: "milk" },
        { zh: "和", py: "hé", en: "and" },
        { zh: "一块", py: "yí kuài", en: "one piece of" },
        { zh: "面包", py: "miànbāo", en: "bread" },
        { zh: "。", py: "", en: "" },
        { zh: "一共", py: "yígòng", en: "altogether" },
        { zh: "二十五", py: "èrshíwǔ", en: "twenty-five" },
        { zh: "块钱", py: "kuài qián", en: "yuan" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "weather",
    title: "天气",
    titleEn: "Weather",
    level: 2,
    english: "The weather is very nice today. The sun is strong, but it is not hot. It might rain in the afternoon. When you go out, don't forget to bring an umbrella.",
    paragraphs: [
      [
        { zh: "今天", py: "jīntiān", en: "today" },
        { zh: "天气", py: "tiānqì", en: "weather" },
        { zh: "很好", py: "hěn hǎo", en: "very good" },
        { zh: "。", py: "", en: "" },
        { zh: "太阳", py: "tàiyáng", en: "sun" },
        { zh: "很大", py: "hěn dà", en: "very strong / big" },
        { zh: "，", py: "", en: "" },
        { zh: "但是", py: "dànshì", en: "but" },
        { zh: "不", py: "bù", en: "not" },
        { zh: "热", py: "rè", en: "hot" },
        { zh: "。", py: "", en: "" },
        { zh: "下午", py: "xiàwǔ", en: "afternoon" },
        { zh: "可能", py: "kěnéng", en: "maybe / possible" },
        { zh: "下雨", py: "xià yǔ", en: "to rain" },
        { zh: "。", py: "", en: "" },
        { zh: "出门", py: "chūmén", en: "to go out" },
        { zh: "的时候", py: "de shíhou", en: "when" },
        { zh: "，", py: "", en: "" },
        { zh: "别", py: "bié", en: "don't" },
        { zh: "忘了", py: "wàng le", en: "forget" },
        { zh: "带", py: "dài", en: "to bring" },
        { zh: "伞", py: "sǎn", en: "umbrella" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "restaurant",
    title: "在餐厅",
    titleEn: "At the restaurant",
    level: 2,
    english: "Waiter, please give me a menu. I would like dumplings and a bowl of soup. Another cup of tea, thank you. This meal is really delicious!",
    paragraphs: [
      [
        { zh: "服务员", py: "fúwùyuán", en: "waiter / waitress" },
        { zh: "，", py: "", en: "" },
        { zh: "请", py: "qǐng", en: "please" },
        { zh: "给", py: "gěi", en: "to give" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "菜单", py: "càidān", en: "menu" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "想", py: "xiǎng", en: "would like / to want" },
        { zh: "吃", py: "chī", en: "to eat" },
        { zh: "饺子", py: "jiǎozi", en: "dumplings" },
        { zh: "和", py: "hé", en: "and" },
        { zh: "一碗", py: "yì wǎn", en: "a bowl of" },
        { zh: "汤", py: "tāng", en: "soup" },
        { zh: "。", py: "", en: "" },
        { zh: "再", py: "zài", en: "again / another" },
        { zh: "来", py: "lái", en: "to bring (an order)" },
        { zh: "一杯", py: "yì bēi", en: "a cup of" },
        { zh: "茶", py: "chá", en: "tea" },
        { zh: "，", py: "", en: "" },
        { zh: "谢谢", py: "xièxie", en: "thank you" },
        { zh: "。", py: "", en: "" },
        { zh: "这顿饭", py: "zhè dùn fàn", en: "this meal" },
        { zh: "真", py: "zhēn", en: "really" },
        { zh: "好吃", py: "hǎochī", en: "delicious" },
        { zh: "！", py: "", en: "" }
      ]
    ]
  },
  {
    id: "weekend",
    title: "周末",
    titleEn: "The weekend",
    level: 2,
    english: "This Saturday I want to go to the park. On Sunday I will watch a movie with a friend. Are you free? Let's go together.",
    paragraphs: [
      [
        { zh: "这个", py: "zhège", en: "this" },
        { zh: "星期六", py: "xīngqīliù", en: "Saturday" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "想", py: "xiǎng", en: "to want" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "公园", py: "gōngyuán", en: "park" },
        { zh: "。", py: "", en: "" },
        { zh: "星期天", py: "xīngqītiān", en: "Sunday" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "和", py: "hé", en: "and / with" },
        { zh: "朋友", py: "péngyou", en: "friend" },
        { zh: "一起", py: "yìqǐ", en: "together" },
        { zh: "看", py: "kàn", en: "to watch" },
        { zh: "电影", py: "diànyǐng", en: "movie" },
        { zh: "。", py: "", en: "" },
        { zh: "你", py: "nǐ", en: "you" },
        { zh: "有空", py: "yǒu kòng", en: "to be free" },
        { zh: "吗", py: "ma", en: "(question particle)" },
        { zh: "？", py: "", en: "" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "一起", py: "yìqǐ", en: "together" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "吧", py: "ba", en: "(suggestion particle)" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "study",
    title: "学中文",
    titleEn: "Learning Chinese",
    level: 3,
    english: "I have been learning Chinese for one year. Chinese characters are not easy, but they are very interesting. Every day I read a short story. Slowly, I can understand more and more.",
    paragraphs: [
      [
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "学", py: "xué", en: "to study" },
        { zh: "中文", py: "Zhōngwén", en: "Chinese (language)" },
        { zh: "一年", py: "yì nián", en: "one year" },
        { zh: "了", py: "le", en: "(change of state)" },
        { zh: "。", py: "", en: "" },
        { zh: "汉字", py: "Hànzì", en: "Chinese characters" },
        { zh: "不", py: "bù", en: "not" },
        { zh: "容易", py: "róngyì", en: "easy" },
        { zh: "，", py: "", en: "" },
        { zh: "可是", py: "kěshì", en: "but" },
        { zh: "很", py: "hěn", en: "very" },
        { zh: "有意思", py: "yǒu yìsi", en: "interesting" },
        { zh: "。", py: "", en: "" },
        { zh: "每天", py: "měi tiān", en: "every day" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "读", py: "dú", en: "to read" },
        { zh: "一个", py: "yí ge", en: "one" },
        { zh: "小", py: "xiǎo", en: "small" },
        { zh: "故事", py: "gùshi", en: "story" },
        { zh: "。", py: "", en: "" },
        { zh: "慢慢地", py: "mànmàn de", en: "slowly" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "看得懂", py: "kàn de dǒng", en: "can understand (by reading)" },
        { zh: "越来越多", py: "yuè lái yuè duō", en: "more and more" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  }
];
