const TEXTS = [
  {
    id: "job",
    title: "申请工作",
    titleEn: "Applying for a job",
    level: 4,
    english: "Recently I saw a company online recruiting a sales manager. I think this position suits me, because I have three years of work experience. I have already sent them my résumé and hope to get an interview.",
    paragraphs: [
      [
        { zh: "最近", py: "zuìjìn", en: "recently" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "在", py: "zài", en: "at / on" },
        { zh: "网上", py: "wǎngshàng", en: "online" },
        { zh: "看到", py: "kàndào", en: "to see / to notice" },
        { zh: "一家", py: "yì jiā", en: "a (company)" },
        { zh: "公司", py: "gōngsī", en: "company" },
        { zh: "招聘", py: "zhāopìn", en: "to recruit" },
        { zh: "销售", py: "xiāoshòu", en: "sales" },
        { zh: "经理", py: "jīnglǐ", en: "manager" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "觉得", py: "juéde", en: "to think / to feel" },
        { zh: "这个", py: "zhège", en: "this" },
        { zh: "职位", py: "zhíwèi", en: "position / post" },
        { zh: "很", py: "hěn", en: "very" },
        { zh: "适合", py: "shìhé", en: "to suit" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "，", py: "", en: "" },
        { zh: "因为", py: "yīnwèi", en: "because" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "有", py: "yǒu", en: "to have" },
        { zh: "三年", py: "sān nián", en: "three years" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "工作", py: "gōngzuò", en: "work" },
        { zh: "经验", py: "jīngyàn", en: "experience" },
        { zh: "。", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "已经", py: "yǐjīng", en: "already" },
        { zh: "把", py: "bǎ", en: "(disposal marker)" },
        { zh: "简历", py: "jiǎnlì", en: "résumé" },
        { zh: "寄", py: "jì", en: "to send" },
        { zh: "给", py: "gěi", en: "to / for" },
        { zh: "他们", py: "tāmen", en: "they / them" },
        { zh: "了", py: "le", en: "(completed action)" },
        { zh: "，", py: "", en: "" },
        { zh: "希望", py: "xīwàng", en: "to hope" },
        { zh: "能够", py: "nénggòu", en: "to be able to" },
        { zh: "获得", py: "huòdé", en: "to obtain" },
        { zh: "面试", py: "miànshì", en: "interview" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "机会", py: "jīhuì", en: "opportunity" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "environment",
    title: "保护环境",
    titleEn: "Protecting the environment",
    level: 4,
    english: "Protecting the environment is everyone's responsibility. If we keep wasting resources and polluting the air, life in the future will become harder and harder. Starting now, we should form the habit of saving water and using fewer plastic bags.",
    paragraphs: [
      [
        { zh: "保护", py: "bǎohù", en: "to protect" },
        { zh: "环境", py: "huánjìng", en: "environment" },
        { zh: "是", py: "shì", en: "to be" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "每个人", py: "měi ge rén", en: "everyone" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "责任", py: "zérèn", en: "responsibility" },
        { zh: "。", py: "", en: "" },
        { zh: "如果", py: "rúguǒ", en: "if" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "继续", py: "jìxù", en: "to continue" },
        { zh: "浪费", py: "làngfèi", en: "to waste" },
        { zh: "资源", py: "zīyuán", en: "resources" },
        { zh: "、", py: "", en: "" },
        { zh: "污染", py: "wūrǎn", en: "to pollute" },
        { zh: "空气", py: "kōngqì", en: "air" },
        { zh: "，", py: "", en: "" },
        { zh: "将来", py: "jiānglái", en: "the future" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "生活", py: "shēnghuó", en: "life" },
        { zh: "会", py: "huì", en: "will" },
        { zh: "越来越", py: "yuè lái yuè", en: "more and more" },
        { zh: "困难", py: "kùnnan", en: "difficult" },
        { zh: "。", py: "", en: "" },
        { zh: "从", py: "cóng", en: "from" },
        { zh: "现在", py: "xiànzài", en: "now" },
        { zh: "开始", py: "kāishǐ", en: "to start" },
        { zh: "，", py: "", en: "" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "应该", py: "yīnggāi", en: "should" },
        { zh: "养成", py: "yǎngchéng", en: "to form (a habit)" },
        { zh: "节约", py: "jiéyuē", en: "to save / to economize" },
        { zh: "用水", py: "yòng shuǐ", en: "to use water" },
        { zh: "、", py: "", en: "" },
        { zh: "少用", py: "shǎo yòng", en: "to use less" },
        { zh: "塑料袋", py: "sùliào dài", en: "plastic bag" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "习惯", py: "xíguàn", en: "habit" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "travel",
    title: "一次旅行",
    titleEn: "A trip",
    level: 4,
    english: "This National Day, a friend and I plan to travel to Yunnan. We will first visit a famous park in Kunming, then go to Dali to see the scenery. The plane tickets are a bit expensive, but this trip will definitely be worth it.",
    paragraphs: [
      [
        { zh: "今年", py: "jīnnián", en: "this year" },
        { zh: "国庆节", py: "Guóqìng jié", en: "National Day" },
        { zh: "，", py: "", en: "" },
        { zh: "我", py: "wǒ", en: "I / me" },
        { zh: "和", py: "hé", en: "and / with" },
        { zh: "朋友", py: "péngyou", en: "friend" },
        { zh: "打算", py: "dǎsuàn", en: "to plan" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "云南", py: "Yúnnán", en: "Yunnan" },
        { zh: "旅行", py: "lǚxíng", en: "to travel" },
        { zh: "。", py: "", en: "" },
        { zh: "我们", py: "wǒmen", en: "we / us" },
        { zh: "计划", py: "jìhuà", en: "to plan / a plan" },
        { zh: "先", py: "xiān", en: "first" },
        { zh: "参观", py: "cānguān", en: "to visit (a place)" },
        { zh: "昆明", py: "Kūnmíng", en: "Kunming" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "著名", py: "zhùmíng", en: "famous" },
        { zh: "公园", py: "gōngyuán", en: "park" },
        { zh: "，", py: "", en: "" },
        { zh: "然后", py: "ránhòu", en: "then" },
        { zh: "再", py: "zài", en: "then / again" },
        { zh: "去", py: "qù", en: "to go" },
        { zh: "大理", py: "Dàlǐ", en: "Dali" },
        { zh: "看", py: "kàn", en: "to see / to look at" },
        { zh: "风景", py: "fēngjǐng", en: "scenery" },
        { zh: "。", py: "", en: "" },
        { zh: "虽然", py: "suīrán", en: "although" },
        { zh: "机票", py: "jīpiào", en: "plane ticket" },
        { zh: "有点儿", py: "yǒudiǎnr", en: "a bit" },
        { zh: "贵", py: "guì", en: "expensive" },
        { zh: "，", py: "", en: "" },
        { zh: "但是", py: "dànshì", en: "but" },
        { zh: "这次", py: "zhè cì", en: "this time" },
        { zh: "旅行", py: "lǚxíng", en: "trip" },
        { zh: "一定", py: "yídìng", en: "definitely" },
        { zh: "很", py: "hěn", en: "very" },
        { zh: "值得", py: "zhíde", en: "to be worth" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "pressure",
    title: "城市里的压力",
    titleEn: "Pressure in the city",
    level: 5,
    english: "As the pace of life keeps speeding up, many young people feel more and more pressure. They have to face fierce competition and take care of their families, so they often feel anxious. Experts suggest that moderate exercise and talking with friends can help ease this tension.",
    paragraphs: [
      [
        { zh: "随着", py: "suízhe", en: "along with" },
        { zh: "生活", py: "shēnghuó", en: "life" },
        { zh: "节奏", py: "jiézòu", en: "pace / rhythm" },
        { zh: "不断", py: "búduàn", en: "continuously" },
        { zh: "加快", py: "jiākuài", en: "to speed up" },
        { zh: "，", py: "", en: "" },
        { zh: "许多", py: "xǔduō", en: "many" },
        { zh: "年轻人", py: "niánqīng rén", en: "young people" },
        { zh: "感到", py: "gǎndào", en: "to feel" },
        { zh: "越来越大", py: "yuè lái yuè dà", en: "greater and greater" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "压力", py: "yālì", en: "pressure" },
        { zh: "。", py: "", en: "" },
        { zh: "他们", py: "tāmen", en: "they" },
        { zh: "既", py: "jì", en: "both (… and)" },
        { zh: "要", py: "yào", en: "must / have to" },
        { zh: "面对", py: "miànduì", en: "to face" },
        { zh: "激烈", py: "jīliè", en: "fierce / intense" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "竞争", py: "jìngzhēng", en: "competition" },
        { zh: "，", py: "", en: "" },
        { zh: "又", py: "yòu", en: "and also" },
        { zh: "要", py: "yào", en: "must / have to" },
        { zh: "照顾", py: "zhàogù", en: "to look after" },
        { zh: "家庭", py: "jiātíng", en: "family" },
        { zh: "，", py: "", en: "" },
        { zh: "因此", py: "yīncǐ", en: "therefore" },
        { zh: "常常", py: "chángcháng", en: "often" },
        { zh: "感到", py: "gǎndào", en: "to feel" },
        { zh: "焦虑", py: "jiāolǜ", en: "anxious" },
        { zh: "。", py: "", en: "" },
        { zh: "专家", py: "zhuānjiā", en: "expert" },
        { zh: "建议", py: "jiànyì", en: "to suggest" },
        { zh: "，", py: "", en: "" },
        { zh: "适当", py: "shìdàng", en: "moderate / appropriate" },
        { zh: "运动", py: "yùndòng", en: "exercise" },
        { zh: "和", py: "hé", en: "and" },
        { zh: "与", py: "yǔ", en: "with" },
        { zh: "朋友", py: "péngyou", en: "friend" },
        { zh: "交流", py: "jiāoliú", en: "to talk / to exchange" },
        { zh: "，", py: "", en: "" },
        { zh: "有助于", py: "yǒu zhù yú", en: "to help / to contribute to" },
        { zh: "缓解", py: "huǎnjiě", en: "to ease / to relieve" },
        { zh: "这种", py: "zhè zhǒng", en: "this kind of" },
        { zh: "紧张", py: "jǐnzhāng", en: "tense / tension" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "情绪", py: "qíngxù", en: "mood / emotion" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "remote",
    title: "远程办公",
    titleEn: "Working remotely",
    level: 5,
    english: "In recent years, remote work has gradually become a common way of working. It not only saves commuting time, but also makes employees' schedules more flexible. However, without effective communication, a team's efficiency may actually fall. Companies therefore need clear rules to protect the quality of work.",
    paragraphs: [
      [
        { zh: "近年来", py: "jìn nián lái", en: "in recent years" },
        { zh: "，", py: "", en: "" },
        { zh: "远程", py: "yuǎnchéng", en: "remote" },
        { zh: "办公", py: "bàngōng", en: "office work" },
        { zh: "逐渐", py: "zhújiàn", en: "gradually" },
        { zh: "成为", py: "chéngwéi", en: "to become" },
        { zh: "一种", py: "yì zhǒng", en: "a kind of" },
        { zh: "普遍", py: "pǔbiàn", en: "common / widespread" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "工作", py: "gōngzuò", en: "work" },
        { zh: "方式", py: "fāngshì", en: "way / method" },
        { zh: "。", py: "", en: "" },
        { zh: "它", py: "tā", en: "it" },
        { zh: "不仅", py: "bùjǐn", en: "not only" },
        { zh: "节省", py: "jiéshěng", en: "to save" },
        { zh: "了", py: "le", en: "(completed action)" },
        { zh: "上下班", py: "shàngxiàbān", en: "commuting (to and from work)" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "时间", py: "shíjiān", en: "time" },
        { zh: "，", py: "", en: "" },
        { zh: "也", py: "yě", en: "also" },
        { zh: "让", py: "ràng", en: "to make / to let" },
        { zh: "员工", py: "yuángōng", en: "employee" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "安排", py: "ānpái", en: "arrangement / schedule" },
        { zh: "更加", py: "gèngjiā", en: "even more" },
        { zh: "灵活", py: "línghuó", en: "flexible" },
        { zh: "。", py: "", en: "" },
        { zh: "然而", py: "rán'ér", en: "however" },
        { zh: "，", py: "", en: "" },
        { zh: "如果", py: "rúguǒ", en: "if" },
        { zh: "缺乏", py: "quēfá", en: "to lack" },
        { zh: "有效", py: "yǒuxiào", en: "effective" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "沟通", py: "gōutōng", en: "communication" },
        { zh: "，", py: "", en: "" },
        { zh: "团队", py: "tuánduì", en: "team" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "效率", py: "xiàolǜ", en: "efficiency" },
        { zh: "反而", py: "fǎn'ér", en: "on the contrary" },
        { zh: "会", py: "huì", en: "will" },
        { zh: "下降", py: "xiàjiàng", en: "to decline" },
        { zh: "。", py: "", en: "" },
        { zh: "因此", py: "yīncǐ", en: "therefore" },
        { zh: "，", py: "", en: "" },
        { zh: "企业", py: "qǐyè", en: "enterprise / company" },
        { zh: "需要", py: "xūyào", en: "to need" },
        { zh: "制定", py: "zhìdìng", en: "to formulate" },
        { zh: "明确", py: "míngquè", en: "clear / explicit" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "规则", py: "guīzé", en: "rule" },
        { zh: "来", py: "lái", en: "in order to" },
        { zh: "保证", py: "bǎozhèng", en: "to guarantee" },
        { zh: "工作", py: "gōngzuò", en: "work" },
        { zh: "质量", py: "zhìliàng", en: "quality" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "ai",
    title: "人工智能的争议",
    titleEn: "The debate over AI",
    level: 6,
    english: "Artificial intelligence is rapidly changing how industries operate. Some say it can greatly raise productivity; others worry it will replace many traditional jobs and even raise ethical disputes. How to balance innovation and regulation has become a question every government must face.",
    paragraphs: [
      [
        { zh: "人工智能", py: "réngōng zhìnéng", en: "artificial intelligence" },
        { zh: "正在", py: "zhèngzài", en: "currently (in the process of)" },
        { zh: "迅速", py: "xùnsù", en: "rapidly" },
        { zh: "改变", py: "gǎibiàn", en: "to change" },
        { zh: "各行各业", py: "gè háng gè yè", en: "every industry" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "运作", py: "yùnzuò", en: "operation" },
        { zh: "方式", py: "fāngshì", en: "way / method" },
        { zh: "。", py: "", en: "" },
        { zh: "有人", py: "yǒurén", en: "some people" },
        { zh: "认为", py: "rènwéi", en: "to think / to hold that" },
        { zh: "它", py: "tā", en: "it" },
        { zh: "能", py: "néng", en: "can" },
        { zh: "大幅", py: "dàfú", en: "by a large margin" },
        { zh: "提高", py: "tígāo", en: "to raise / to improve" },
        { zh: "生产力", py: "shēngchǎnlì", en: "productivity" },
        { zh: "，", py: "", en: "" },
        { zh: "也", py: "yě", en: "also" },
        { zh: "有人", py: "yǒurén", en: "some people" },
        { zh: "担心", py: "dānxīn", en: "to worry" },
        { zh: "它", py: "tā", en: "it" },
        { zh: "会", py: "huì", en: "will" },
        { zh: "取代", py: "qǔdài", en: "to replace" },
        { zh: "大量", py: "dàliàng", en: "a large number of" },
        { zh: "传统", py: "chuántǒng", en: "traditional" },
        { zh: "岗位", py: "gǎngwèi", en: "job post" },
        { zh: "，", py: "", en: "" },
        { zh: "甚至", py: "shènzhì", en: "even" },
        { zh: "引发", py: "yǐnfā", en: "to trigger" },
        { zh: "伦理", py: "lúnlǐ", en: "ethics" },
        { zh: "方面", py: "fāngmiàn", en: "aspect" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "争议", py: "zhēngyì", en: "controversy" },
        { zh: "。", py: "", en: "" },
        { zh: "如何", py: "rúhé", en: "how" },
        { zh: "在", py: "zài", en: "between / at" },
        { zh: "创新", py: "chuàngxīn", en: "innovation" },
        { zh: "与", py: "yǔ", en: "and" },
        { zh: "监管", py: "jiānguǎn", en: "regulation / supervision" },
        { zh: "之间", py: "zhījiān", en: "between" },
        { zh: "取得", py: "qǔdé", en: "to obtain" },
        { zh: "平衡", py: "pínghéng", en: "balance" },
        { zh: "，", py: "", en: "" },
        { zh: "已", py: "yǐ", en: "already" },
        { zh: "成为", py: "chéngwéi", en: "to become" },
        { zh: "各国", py: "gè guó", en: "various countries" },
        { zh: "政府", py: "zhèngfǔ", en: "government" },
        { zh: "必须", py: "bìxū", en: "must" },
        { zh: "面对", py: "miànduì", en: "to face" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "课题", py: "kètí", en: "issue / task" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  },
  {
    id: "reading",
    title: "阅读的意义",
    titleEn: "The meaning of reading",
    level: 6,
    english: "In an age of exploding information, people are used to skimming fragmented content and rarely read in depth. Real reading does not only add knowledge; it also trains critical thinking, so one can keep independent judgment in a complicated society. In that sense, reading is an irreplaceable form of intellectual cultivation.",
    paragraphs: [
      [
        { zh: "在", py: "zài", en: "in / at" },
        { zh: "信息", py: "xìnxī", en: "information" },
        { zh: "爆炸", py: "bàozhà", en: "explosion" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "时代", py: "shídài", en: "era" },
        { zh: "，", py: "", en: "" },
        { zh: "人们", py: "rénmen", en: "people" },
        { zh: "习惯于", py: "xíguàn yú", en: "to be used to" },
        { zh: "浏览", py: "liúlǎn", en: "to browse" },
        { zh: "碎片化", py: "suìpiànhuà", en: "fragmented" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "内容", py: "nèiróng", en: "content" },
        { zh: "，", py: "", en: "" },
        { zh: "却", py: "què", en: "yet / but" },
        { zh: "很少", py: "hěn shǎo", en: "rarely" },
        { zh: "进行", py: "jìnxíng", en: "to carry out" },
        { zh: "深入", py: "shēnrù", en: "in-depth" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "阅读", py: "yuèdú", en: "reading" },
        { zh: "。", py: "", en: "" },
        { zh: "真正", py: "zhēnzhèng", en: "genuine / real" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "阅读", py: "yuèdú", en: "reading" },
        { zh: "不仅", py: "bùjǐn", en: "not only" },
        { zh: "能", py: "néng", en: "can" },
        { zh: "增长", py: "zēngzhǎng", en: "to increase" },
        { zh: "知识", py: "zhīshi", en: "knowledge" },
        { zh: "，", py: "", en: "" },
        { zh: "更能", py: "gèng néng", en: "can even more" },
        { zh: "培养", py: "péiyǎng", en: "to cultivate" },
        { zh: "批判性", py: "pīpànxìng", en: "critical" },
        { zh: "思维", py: "sīwéi", en: "thinking" },
        { zh: "，", py: "", en: "" },
        { zh: "使", py: "shǐ", en: "to make / to enable" },
        { zh: "人", py: "rén", en: "a person" },
        { zh: "在", py: "zài", en: "in" },
        { zh: "复杂", py: "fùzá", en: "complicated" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "社会", py: "shèhuì", en: "society" },
        { zh: "中", py: "zhōng", en: "in / among" },
        { zh: "保持", py: "bǎochí", en: "to maintain" },
        { zh: "独立", py: "dúlì", en: "independent" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "判断", py: "pànduàn", en: "judgment" },
        { zh: "。", py: "", en: "" },
        { zh: "从", py: "cóng", en: "from" },
        { zh: "这个", py: "zhège", en: "this" },
        { zh: "意义上", py: "yìyì shàng", en: "in this sense" },
        { zh: "说", py: "shuō", en: "to say" },
        { zh: "，", py: "", en: "" },
        { zh: "阅读", py: "yuèdú", en: "reading" },
        { zh: "是", py: "shì", en: "to be" },
        { zh: "一种", py: "yì zhǒng", en: "a kind of" },
        { zh: "不可替代", py: "bùkě tìdài", en: "irreplaceable" },
        { zh: "的", py: "de", en: "(attributive)" },
        { zh: "精神", py: "jīngshén", en: "intellectual / spiritual" },
        { zh: "修养", py: "xiūyǎng", en: "cultivation" },
        { zh: "。", py: "", en: "" }
      ]
    ]
  }
];
